### ISSUE TITLE
Missing .exe 

### ISSUE THREAD

**Issue by bambussmoker** [colinhartigan/valorant-rpc#1]
i might sound like a noob but i didnt find any .exe file should i take the .batch file?

**Comment by SaifAqqad** [comment]
You can download it from [Releases](https://github.com/colinhartigan/valorant-rpc/releases)

**Comment by Kakashi0307** [comment]
> You can download it from [Releases](https://github.com/colinhartigan/valorant-rpc/releases)

Thanks
