### ISSUE TITLE
EDIT: Getting errors with some scripts

### ISSUE THREAD

**Issue by Metoku** [colinhartigan/valorant-rpc#10]
![image](https://user-images.githubusercontent.com/59681368/112183503-472ba800-8c39-11eb-886b-bd2504cb2194.png)
So after I go to agent select I'm getting errors like this. I tested with spike rush and custom

**Comment by Transpirations** [comment]
m having the same issue

**Comment by deva0000** [comment]
same

**Comment by nxs-neo** [comment]
Do u have any fix for this?

**Comment by colinhartigan** [comment]
try the [latest release?](https://github.com/colinhartigan/valorant-rpc/releases/tag/v2.1)

**Comment by rxri** [comment]
Shouldn't be closed.
![image](https://user-images.githubusercontent.com/9348108/114314183-f271a380-9af9-11eb-9b20-f3b512be5973.png)
I'm trying to debug it and literally or this endpoint doesn't exist or uuid doesn't exist since api throws resource not found.

edit: found issue. #18
