### ISSUE TITLE
?

### ISSUE THREAD

**Issue by k1zn** [colinhartigan/valorant-rpc#100]
When I download new version and start it from Downloads, i see this:
![image](https://user-images.githubusercontent.com/46452865/151185363-fe97b0f3-3664-43cb-83b0-7731d061f80c.png)
After moving valorant-rpc.exe to C:\ everything ran successfully

**Comment by k1zn** [comment]
Ah, not even that. After transferring to the C:\ drive, the program asked to select the language, then the exact same error.

**Comment by k1zn** [comment]
I don't have lockfile in \\Config\\

**Comment by k1zn** [comment]
If i launch VALORANT and then valorant-rpc.exe then all is normal

**Comment by colinhartigan** [comment]
the lockfile only exists while the game is running. the first time you run the app VALORANT must be open, but after that it will start auto-launching the game
