### ISSUE TITLE
Waiting for rpc client

### ISSUE THREAD

**Issue by a20kavis** [colinhartigan/valorant-rpc#101]
It worked perfectly fine yesterdaay but today its suddenly not, giving this issue

https://i.imgur.com/m3oamv7.png

**Comment by colinhartigan** [comment]
this is likely tied to Discord's big API outage, id give it an hour and retry

**Comment by a20kavis** [comment]
> this is likely tied to Discord's big API outage, id give it an hour and retry

that's a good shout, i'll leave it for now then

**Comment by a20kavis** [comment]
It's fixed! Discord got their shit together now. Thanks for the quick help :)
