### ISSUE TITLE
Riot authentication error

### ISSUE THREAD

**Issue by HarvsoDev** [colinhartigan/valorant-rpc#11]
Program won't authenticate with riot.
Also getting script execution errors when going into agent select.
_[!] could not authenticate with Riot for enhanced presence, check username/password!_

**Comment by colinhartigan** [comment]
what's your region?

**Comment by HarvsoDev** [comment]
EU West

**Comment by colinhartigan** [comment]
currently it only supports NA

completely forgot about other regions - will include them in a future update, but you should still be able to use it with a blank username and password, it just won't support party invites or agent details in the presence

**Comment by HarvsoDev** [comment]
rip, still a cool project. i look forward to eu support!
