### ISSUE TITLE
 Feature Request: Party Invites

### ISSUE THREAD

**Issue by NaiveInvestigator** [colinhartigan/valorant-rpc#111]
Could we re-add that feature back on the new version?

**Comment by colinhartigan** [comment]
the invite feature in v2 was very experimental, janky to set up, and ultimately not very useful due to limitations set by discord, so native discord party invites are scrapped. i created another way to invite with links a while ago, but i'm still unsure if it will ever be released.

**Comment by NaiveInvestigator** [comment]
Could we add that to a experimental branch instead? Would really a be neat thing imho.
