### ISSUE TITLE
Add Fade

### ISSUE THREAD

**Issue by GenzPN** [colinhartigan/valorant-rpc#112]
![image](https://user-images.githubusercontent.com/39546317/165739413-f792fda1-8905-44aa-bb16-30a6506f4cd9.png)

**Comment by Techconix** [comment]
why close it @colinhartigan

**Comment by colinhartigan** [comment]
she's added

**Comment by Techconix** [comment]
but the last update is from Feb 1

**Comment by colinhartigan** [comment]
no update required
