### ISSUE TITLE
Error 13 Permission denied

### ISSUE THREAD

**Issue by zLxisFX** [colinhartigan/valorant-rpc#113]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 32, in __init__
  File "src\utilities\program_data.py", line 22, in update_file_location
  File "src\utilities\program_data.py", line 36, in modify_isntalls
PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\valorant-tools\\installs.json'

**Comment by Pikachu051** [comment]
Launch the game first, then launch the program.

Next time, you can launch the program and the program will launch the game for you automatically.

**Comment by zLxisFX** [comment]
still does the same thing

**Comment by HighError** [comment]
Run as administrator or configure public folder access

**Comment by HighError** [comment]
Public folder:
Right mouse click on the folder "C:\ProgramData\valorant-tools" -> Properties

1)Security
![image](https://user-images.githubusercontent.com/46526245/170493269-7978db15-b9a6-4077-9935-d7a3a23005da.png)
