### ISSUE TITLE
Pls Help

### ISSUE THREAD

**Issue by Brick0-0** [colinhartigan/valorant-rpc#119]
_   _____   __   ____  ___  ___   _  ________
| | / / _ | / /  / __ \/ _ \/ _ | / |/ /_  __/__________  ____
| |/ / __ |/ /__/ /_/ / , _/ __ |/    / / / /___/ __/ _ \/ __/
|___/_/ |_/____/\____/_/|_/_/ |_/_/|_/ /_/     /_/ / .__/\__/
                                                  /_/ v3.2.1

attempting to autodetect region
the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "valclient\client.py", line 907, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Brick\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 73, in activate
  File "valclient\client.py", line 912, in __get_lockfile
valclient.exceptions.LockfileError: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 50, in __init__
  File "src\startup.py", line 159, in check_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?
press enter to exit...

**Comment by yanNotDev** [comment]
read the second last line of your issue

**Comment by Coder-bots** [comment]
i have same problem

**Comment by EMREOYUN** [comment]
I guess you are starting the program for the very first time. Make sure VALORANT is running and you are gone through the main menu, then run the program.

**Comment by colinhartigan** [comment]
make sure valorant is running on the first launch
