### ISSUE TITLE
v2.1 minor issue: "an update is available 2.1" -> 2.0

### ISSUE THREAD

**Issue by deva0000** [colinhartigan/valorant-rpc#12]
Looks like the script errors from v2.0 are fixed and up to this moment its working fine ;) 

When I open the program I recieve a message saying that a update is available, even though Im using the last version:
https://prnt.sc/10w5s6v

This doesnt affect me at all, just reporting for helping you perfect the app :)

**Comment by colinhartigan** [comment]
yeah i'm looking into it, github is weird with how it labels releases

glad it fixed your other problems though :)

**Comment by colinhartigan** [comment]
fixed the github problem; there was also an issue with version checking so I've edited the [release](https://github.com/colinhartigan/valorant-rpc/releases/tag/v2.1)

let me know if it's not working

**Comment by deva0000** [comment]
apparently working as intended now, I'll let you know if anything comes up
