### ISSUE TITLE
[Feature Request] Ascendant Rank + Pearl Map

### ISSUE THREAD

**Issue by EMREOYUN** [colinhartigan/valorant-rpc#120]
In the latest update, Valorant added Ascendant Rank and a brand new map "Pearl"

**Comment by Techconix** [comment]
I know that there was no updated need when Fade was added.
Did you even check if Pearl and Ascendant even showed up on there? I think it uses the Riot API for the stuff so there may be no need to update.

**Comment by EMREOYUN** [comment]
I can't right now because I'm away from constant internet(I still can't test Ascendant due to my rank) but if this is the case, why the source code has assets folder that contains all maps expect Pearl, characters including Fade, and ranks except Ascendant?

**Comment by colinhartigan** [comment]
the assets have been uploaded to the discord RPC app. no update is required
