### ISSUE TITLE
File Doesn't Exist

### ISSUE THREAD

**Issue by ipuppyyt** [colinhartigan/valorant-rpc#125]
**Traceback (most recent call last):
  File "valclient\client.py", line 907, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\iPuppyYT\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'**

**Comment by colinhartigan** [comment]
game has to be running

**Comment by itsTyrion** [comment]
> game has to be running

![image](https://user-images.githubusercontent.com/17730120/212226822-8c81fc27-03f3-4984-96ce-e0123735c45c.png)
the readme says otherwise

**Comment by janinhasz** [comment]
@itsTyrion it'll do that after your first launch
