### ISSUE TITLE
Client ID and Client secret not present in config.js

### ISSUE THREAD

**Issue by MrFoxyOfficial** [colinhartigan/valorant-rpc#138]
I've been trying to follow the steps via Wiki for creating the [Discord application](https://github.com/colinhartigan/valorant-rpc/wiki/Creating-a-Discord-Application-for-VALORANT-RPC/d84360822e778479113e411fdcf9751d34e5ccc7) and how to get to [config.json](https://github.com/colinhartigan/valorant-rpc/blob/v2/README.md#editing-the-configuration) but I don't seem to find the fields below:
![image](https://user-images.githubusercontent.com/1783339/222903476-41adfe14-8f15-4b6c-9cf0-f04ad0453c59.png)

All that I have in the config.json is: 
```{"version": "v3.2.2", "region": ["eu", ["na", "eu", "latam", "br", "ap", "kr", "pbe"]], "client_id": 1081560368326909962, "presence_refresh_interval": 3, "locale": ["en-US", ["en-US", "ar-AE", "de-DE", "es-ES", "es-MX", "fr-FR", "id-ID", "it-IT", "ja-JP", "ko-KR", "pl-PL", "pt-BR", "ru-RU", "th-TH", "tr-TR", "vi-VN", "zh-TW"]], "presences": {"menu": {"show_rank_in_comp_lobby": true}, "modes": {"all": {"small_image": ["agent", ["rank", "agent", "map"]], "large_image": ["map", ["rank", "agent", "map"]]}, "range": {"show_rank_in_range": true}}}, "startup": {"game_launch_timeout": 50, "presence_timeout": 60, "show_github_link": true, "auto_launch_skincli": true}}```

Would love to get this to work, as it's a lot easier to invite people to your lobby 😅😅

**Comment by colinhartigan** [comment]
unfortunately that feature was highly experimental and on a different version (v2). in short, discord only allows you to make test applications which have a maximum of 50 users, and for party invites to work, everyone must be using the app. its appeal quickly falls apart when you want to invite someone who doesn't have access to your specific application.
