### ISSUE TITLE
NotWpr

### ISSUE THREAD

**Issue by RiSPECT** [colinhartigan/valorant-rpc#14]
![image](https://user-images.githubusercontent.com/81699543/113166755-e61d5900-9264-11eb-80a3-b4aee2186d0d.png)
my rich presence is stuck here did everything in the read me prperly
just the timer goes on and also is there a way to change that logo?

**Comment by Oogway443** [comment]
i have the same issue

**Comment by rxri** [comment]
Fixed in release 2.2 - added another regions.
