### ISSUE TITLE
Windows Defender flagged the exe file as a threat

### ISSUE THREAD

**Issue by caulmseh** [colinhartigan/valorant-rpc#17]
I'm sure that this is false positive detection mainly because the app is new and still in development
https://imgur.com/a/msuTMki
![Screenshot (478)](https://user-images.githubusercontent.com/51788724/114288057-ba894280-9a9e-11eb-9888-7c6d14b6e168.png)

**Comment by colinhartigan** [comment]
yup, if you still feel uncomfortable using it you can [build the exe](https://github.com/colinhartigan/valorant-rpc/blob/v2/build.bat)
