### ISSUE TITLE
KeyError: 'MatchID'

### ISSUE THREAD

**Issue by Cr1stalz** [colinhartigan/valorant-rpc#20]
![image](https://user-images.githubusercontent.com/43808665/114399343-6764dc00-9bd3-11eb-9123-33f1962ca85e.png)
 Region: RU
 Server: EU

**Comment by rxri** [comment]
Should be fixed if you changed ``region`` to ``eu`` in %appdata%/valorant-rpc :)
![image](https://user-images.githubusercontent.com/9348108/114399930-c01b8100-9ba1-11eb-9f58-d42452bb3832.png)

**Comment by Cr1stalz** [comment]
can you make translate for all region?

and thx

**Comment by rxri** [comment]
I mean it is in readme tho
![image](https://user-images.githubusercontent.com/9348108/114400097-e93c1180-9ba1-11eb-82df-d2fe2e9eb124.png)

**Comment by Cr1stalz** [comment]
![image](https://user-images.githubusercontent.com/43808665/114401818-da6f5200-9bd5-11eb-87ac-005f95848584.png)

**Comment by Cr1stalz** [comment]
EU work, but RUS not

**Comment by colinhartigan** [comment]
change it to EU and it should work

**Comment by rxri** [comment]
Obviously, there is no RUS server. There is only EU, KO, NA and AP.
