### ISSUE TITLE
I cannot find the EXE file

### ISSUE THREAD

**Issue by bhushan2712** [colinhartigan/valorant-rpc#21]
Hey there buddy! Can you let me know where is the RPC EXECUTABLE file in the code?

**Comment by rxri** [comment]
You need to compile it first if you want to have executable and then you will find it in `dist` folder. Otherwise just use installer.

**Comment by Shmalle** [comment]
I couldnt locate the installer, I just did `pip install -r .\requirements.txt` and ran the build.bat, exe in build-folder and dist-folder wouldnt launch the program but `python .\main.py` did.
EDIT: It doesnt show the "Ask to join" button tho.
I just scrolled down here https://pythonrepo.com/repo/colinhartigan-valorant-rpc and downloaded it
