### ISSUE TITLE
How did you get the endpoints?

### ISSUE THREAD

**Issue by frostysecurethebag** [colinhartigan/valorant-rpc#22]
Im kinda new to this api thingy, 
I checked the apis in riot's site but I didn't find any API that gave me ingame data

**Comment by colinhartigan** [comment]
you can see some of the endpoints the client uses in %LOCALAPPDATA%\VALORANT\Saved\Logs\ShooterGame.log

i'd join [this discord server](https://discord.gg/ApJ4PT57ym) where there are many people who can help you out with learning the client api
