### ISSUE TITLE
Images not working when using discord application

### ISSUE THREAD

**Issue by Shmalle** [colinhartigan/valorant-rpc#23]
I wanted to use the "ask to join" feature, but as it turns out, it doesnt show any images. When uploading them to the Arts Assets section in the devs portal, it just gets deleted after saving.

**Comment by colinhartigan** [comment]
it takes a few minutes for discord to process the assets, wait a few minutes and refresh

**Comment by Shmalle** [comment]
> it takes a few minutes for discord to process the assets, wait a few minutes and refresh

Just firgured that out, thanks for the fast response. What about the ask-to-join button? Its not appearing

**Comment by colinhartigan** [comment]
you have to be in an open party
