### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by Karo1ina** [colinhartigan/valorant-rpc#25]
the RPC is stuck for me on one area so when i go into game it will say 1:1 and then just not refresh

**Comment by colinhartigan** [comment]
what mode is this happening in?

**Comment by iiTatoZ** [comment]
playing on breeze rpc is stuck saying solo queue with time rather than showing picture of map and character with the score

**Comment by Karo1ina** [comment]
NVM it fixed lol

**Comment by colinhartigan** [comment]
ok lmao
