### ISSUE TITLE
No Image in Pregame/Agent Pick phase

### ISSUE THREAD

**Issue by Fablo020** [colinhartigan/valorant-rpc#26]
Hello, is it possible to add the map picture while picking the agent?
~or at least the default game_icon.png?~ _Already found out how to do this. Changed the "large_image=" to "game_icon"._

Screenshots:
![Screenshot](https://i.imgur.com/mbv3ama.png)
![Screenshot](https://i.imgur.com/keSaEke.png)

**Edit:** It seems like the Pregame section doesn't work at all.
It doesn't show "Selecting - " or "locked - " like in match_session.py

**Edit #2:** 
"Selecting" and "locked" does work but they have a "?" behind the dash see Screenshot 2 and there is no (white) game icon like in the first Screenshot.

**Comment by colinhartigan** [comment]
i must've inadvertently broken pregame - it all used to work as expected

will take a look into this

**Comment by matthew-paul** [comment]
Hi, I think I've fixed this with my pull request. Could you please review it?

Thanks
