### ISSUE TITLE
NOt Fetching When Ingame

### ISSUE THREAD

**Issue by ipunjabigamer** [colinhartigan/valorant-rpc#27]
when i am in game its not showing 
its shows i am in queue

**Comment by ipunjabigamer** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/43644687/117412488-7b7dce00-af32-11eb-94ee-0c66b314e680.png)

**Comment by Fablo020** [comment]
Did you enter your correct region?

> _Navigate to %APPDATA%\valorant-rpc and open config.json with your favorite text editor_

> **press WIN+R, type %APPDATA%\valorant-rpc then press enter**
> change this to your client's region, can be found in settings -> about -> game shard

e.g. "EU", default is "NA"

**Comment by cleitonpin** [comment]
oh, there is no explaining step by step to change the region, I could put it there, I was also having this problem

**Comment by Fablo020** [comment]
> oh, there is no explaining step by step to change the region, I could put it there, I was also having this problem

There is: https://github.com/colinhartigan/valorant-rpc#editing-the-configuration

**Comment by Lakhwinder123** [comment]
i play on mumbai server, so which region i put?

**Comment by ipunjabigamer** [comment]
its not working i changed my region to ind

**Comment by sudhxnva** [comment]
@Lakhwinder123 If you mean India by 'ind', then your region should be set to 'ap' (for Asia Pacific), not 'ind'
