### ISSUE TITLE
Failed Script Main

### ISSUE THREAD

**Issue by testificate2000** [colinhartigan/valorant-rpc#31]
I did the  target thing, then clicked on the valotant shortcut,
Opens command Prompt and shows this

And nothing happens

I have to manually open valo, then open RPC
![image](https://user-images.githubusercontent.com/63576875/123398565-50723b00-d5c1-11eb-9581-b5bdb52504b4.png)

Please help.

**Comment by Pg-Pi3Gey** [comment]
is you discord working before executings the script/vaorant-rpc program ??
