### ISSUE TITLE
Failure to execute script main

### ISSUE THREAD

**Issue by NoteStars** [colinhartigan/valorant-rpc#34]
When trying to install the new version of valorant rpc v2.5, rpc fails to execute main script
![07-07-21_00_08_37s](https://user-images.githubusercontent.com/86938788/124715665-17d33b00-deb8-11eb-8093-6d2696831204.png)

**Comment by Metoku** [comment]
same problem though it is installed but cannot run the app itself

**Comment by HighError** [comment]
I also have this problem

**Comment by LukaMrt** [comment]
I have this problem too. I tried some things to fix this but nothing worked :
- uninstall all versions of valorant rpc and install 2.5 version
- install 2.5version while 2.4 version is installed
- manually install the iso8601 package

When the error occurs, the command prompte automatically closes itself.
I also noticed that the installation of the 2.5 version doesn't create the config folder. I manually created it with the config.json file. Even with that the command prompt closes itself without letting me watch the error (i had to record my screen).

**Comment by jordanyoong1** [comment]
Can confirmed, same problem

**Comment by colinhartigan** [comment]
oh shoot, i recently reinstalled python and forgot to install all of my modules before building the executable

i'll fix this very soon

**Comment by yofukashino** [comment]
Well done Moj kardi bete

**Comment by colinhartigan** [comment]
resolved in [v3.0.0](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.0.0)
