### ISSUE TITLE
failure to execute script main help please

### ISSUE THREAD

**Issue by pokichu** [colinhartigan/valorant-rpc#37]
hi everytime i'm trying to lunch the app this error shows up and the app closes its own please help me hear i like this app its happening from version 2.5

**Comment by Metoku** [comment]
#34 its already mentioned here bro. You will have to wait for the owner to fix his app.

**Comment by colinhartigan** [comment]
i will be rolling back version 2.5 and will fix all of these bugs in the v3 rewrite. the current codebase was not built for expandability and is too troublesome to maintain for each update

**Comment by colinhartigan** [comment]
resolved in [v3.0.0](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.0.0)
