### ISSUE TITLE
Simply dosent work

### ISSUE THREAD

**Issue by baobao2167** [colinhartigan/valorant-rpc#38]
when i open it it jus shows a error and closes the window immediately (2.5) (2.4) also dosent work when i join a unrated it still shows lobby and only works in custom games.

**Comment by colinhartigan** [comment]
i will be rolling back version 2.5 and will fix all of these bugs in the v3 rewrite. the current codebase was not built for expandability and is too troublesome to maintain for each update

**Comment by colinhartigan** [comment]
resolved in [v3.0.0](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.0.0)
