### ISSUE TITLE
Valorant RPC 2.5 

### ISSUE THREAD

**Issue by Tresillo2017** [colinhartigan/valorant-rpc#41]
Hey, I just install valorant rpc 2.5. But it doesn't open. 

This is what its says when I open it
[image](https://user-images.githubusercontent.com/56476330/125166167-a8509a80-e19a-11eb-9516-31968b62838c.png)

**Comment by LoredCast** [comment]
The installer didn't work for me aswell, try cloning and executing main.py from a python shell. ReadMe should add an option for building/running from source.

**Comment by HighError** [comment]
https://github.com/colinhartigan/valorant-rpc/issues/37

**Comment by HighError** [comment]
> Hey, I just install valorant rpc 2.5. But it doesn't open.
> 
> This is what its says when I open it
> [image](https://user-images.githubusercontent.com/56476330/125166167-a8509a80-e19a-11eb-9516-31968b62838c.png)

https://github.com/colinhartigan/valorant-rpc/issues/37

**Comment by OzamaDz** [comment]
> Hey, I just install valorant rpc 2.5. But it doesn't open.
> 
> This is what its says when I open it
> [image](https://user-images.githubusercontent.com/56476330/125166167-a8509a80-e19a-11eb-9516-31968b62838c.png)

i have installed the all libraries & i have the same problem.
![Screenshot (16)](https://user-images.githubusercontent.com/72144299/125306634-470a0200-e327-11eb-8b98-ca5ad1bd0b76.png)

**Comment by colinhartigan** [comment]
im in the process of completely rewriting the program, this problem will be fixed with it

**Comment by colinhartigan** [comment]
ive put out some beta builds in my [discord server](https://discord.gg/uGuswsZwAT) if you guys want to check them out as a temporary solution

**Comment by colinhartigan** [comment]
resolved in [v3.0.0](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.0.0)
