### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by dotatlas** [colinhartigan/valorant-rpc#45]
I used the install exe to, well, install it. I boot up the rpc executable while valorant is open, it shows the command terminal for like 1/2 a second, then closes. it just does nothing. Ive tried doing the auto boot up with valorant by changing the launch target but it never did anything as expected, yet I can still launch valorant normally, just no RPC

**Comment by colinhartigan** [comment]
versions <= 2.5 are unsupported in favor of v3, you can find the latest beta in [the discord server](https://discord.gg/uGuswsZwAT)
