### ISSUE TITLE
(new): Make GitHub button in discord RPC optional

### ISSUE THREAD

**Issue by rxri** [colinhartigan/valorant-rpc#46]
.

**Comment by colinhartigan** [comment]
will add this as a config option in next update

**Comment by colinhartigan** [comment]
released in [v3.1.0](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.1.0)

**Comment by rxri** [comment]
![image](https://user-images.githubusercontent.com/9348108/132093447-211fdc97-c39c-4c58-a398-5cb8465f9d89.png)

😞

**Comment by colinhartigan** [comment]
i had to take the release down due to a bug but it'll be back up soon :(
