### ISSUE TITLE
Error in Range

### ISSUE THREAD

**Issue by BearTS** [colinhartigan/valorant-rpc#72]
```cmd.
the program encountered an error: please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "src\presence\presence.py", line 35, in main_loop
  File "src\presence\presence.py", line 65, in update_presence
  File "src\presence\presences\ingame.py", line 18, in presence
  File "src\presence\presences\ingame_presences\range.py", line 18, in __init__
ValueError: not enough values to unpack (expected 2, got 0)
press enter to exit...
```
This happens when i go in range

**Comment by colinhartigan** [comment]
riot changed the data that's sent in presences so i need to adjust for this

thanks for sending

**Comment by BearTS** [comment]
nice seems to be fixed in range, havent tried in game , because after pregame, it didnt showed me anything in console nor the presence updated on discord. Will try it and let you know if latest build works for in game as well

**Comment by BearTS** [comment]
![image](https://user-images.githubusercontent.com/65192718/134697505-7e3bf6e2-1925-483a-a542-d826c4651217.png)
yeah doesnt work, i m in game playing with 1-0 score

**Comment by colinhartigan** [comment]
[fixed](https://github.com/colinhartigan/valorant-rpc/releases/tag/v3.1.3)
