### ISSUE TITLE
When I launch valorant, I get this message, and then it closes and nothing happens

### ISSUE THREAD

**Issue by NickB301** [colinhartigan/valorant-rpc#8]
https://cdn.discordapp.com/attachments/773750677113012264/821910993956896788/unknown.png

**Comment by colinhartigan** [comment]
download the [newest release](https://github.com/colinhartigan/valorant-rpc/releases/tag/v1.3) and follow the installation instructions

**Comment by NickB301** [comment]
Thank you it worked!

**Comment by colinhartigan** [comment]
no problem :)
