### ISSUE TITLE
Windows terminal don't hide after start

### ISSUE THREAD

**Issue by HighError** [colinhartigan/valorant-rpc#86]
Windows terminal don't hide after start discord-rpc
![image](https://user-images.githubusercontent.com/46526245/141838147-eabdad7a-1f24-4618-823a-97e18f9a1a94.png)

**Comment by rxri** [comment]
Because Windows Terminal doesn't have this functionality? (sarcastic question)
Only conhost has, so if you want to hide terminal, use conhost instead of Windows Terminal

**Comment by colinhartigan** [comment]
yea windows terminal doesnt have functionality to hide
