### ISSUE TITLE
Windows defender marking .exe as virus

### ISSUE THREAD

**Issue by 0xMillyByte** [colinhartigan/valorant-rpc#9]
what title said:
![image](https://user-images.githubusercontent.com/48217459/112164513-3ace2d80-8bee-11eb-866f-fa399867d7d3.png)

Translated, it says 'failed - virus detected'

**Comment by colinhartigan** [comment]
go to chrome://downloads/ and you should be able to select an option to 'download it anyway' from there

**Comment by 0xMillyByte** [comment]
Nope, doesn't seem to be working. It linked me to an info page saying that it's being blocked by windows defender. 
Why would windows defender mark this as a virus?
Should i temporarily disable it?

**Comment by colinhartigan** [comment]
yup
