### ISSUE TITLE
Valorant banning RPC users 

### ISSUE THREAD

**Issue by nxs-neo** [colinhartigan/valorant-rpc#91]
Several of my friends had their accounts permanently suspended for using third party software after using this. Riot won't revert the bans either.

**Comment by colinhartigan** [comment]
how do they know it's specifically due to this? i've been using this and other VALORANT apps i've written for much longer than anyone else with no problems

**Comment by nxs-neo** [comment]
They msged riot support asking to revert the ban and said they only used
the rpc. Riot msged back with it provides some sort of advantage or
something. Can u please like clarify with riot or something.

**Comment by colinhartigan** [comment]
its extremely unlikely that riot would notice something like this (or even if they caught it with vanguard they'd likely not care)... i've shared it with a few rioters and they haven't said i'm not allowed to use it. there's also other apps which use the same api and to my knowledge nobody has ever been banned or had problems. 

i'd say it's likely your friend used some other app that actually gave them an advantage and there's not anything i can do.
