### ISSUE TITLE
Autodetect Region

### ISSUE THREAD

**Issue by theelderlydied** [colinhartigan/valorant-rpc#94]
![image](https://user-images.githubusercontent.com/74889702/149360495-f6d2e1bf-eb8e-4ebd-b00b-f4e0d7c08bfd.png)

**Comment by shimizu-izumi** [comment]
I have the same problem and you most likely don't have a lockfile in that directory just like me

**Comment by itispey** [comment]
Same for me. There isn't any lockfile in %localappdata% path.
So, is there any way to create that lockfile or find any solution?

**Comment by shimizu-izumi** [comment]
Start the game then start the RPC that will fix it because the lockfile is created when you start Valorant

**Comment by colinhartigan** [comment]
see @LeonHenning's solution
